name: Run Java File

on:
  push:
    branches: ["master"]

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java file
        run: javac -d . src/PracticePackage/Practice_1.java

      - name: Run Java program
        run: java PracticePackage.Practice_1
